### ISSUE TITLE
Completed User Auth

### ISSUE THREAD

**Issue by Isabelleshafran** [Isabelleshafran/IntoTheGloss#2]
Hi Joe, 

Please see below for link to Heroku site. 

https://isabelle-glossier.herokuapp.com/#/

**Comment by JoeBumbaca** [comment]
Hey Isabelle, looks good.  I definitely want to figure out that double click issue. . . weird.  Other than that, I would remove the underline (on hover) from the category headers in the nav bar.  And remove all styling (on hover) from the Into The Gloss title.  You can check out the behavior on their site to see what I mean.  Once that's done, I'll close this issue.

**Comment by JoeBumbaca** [comment]
Looks, good.  Thanks for making the changes.
